### ISSUE TITLE
I can't use this repository 

### ISSUE THREAD

**Issue by RoskoMx** [Sven-Bo/streamlit-quiztube#4]
Hello, Sven. One question, if I copy this repository and try to run the application from Satreamlit Sharing, the application does not appear. I don't get any errors, it just keeps loading. I haven't made any changes, do you know why I can't run it from my Github?

**Comment by Sven-Bo** [comment]
I recommend cloning the repository and initially running it locally on your machine before deploying. It's challenging to diagnose the issue from afar, especially without any error messages. Consequently, I cannot provide much assistance in this case, and I will be closing the issue. Please be aware that my YouTube tutorials are mainly for educational purposes. Managing over 100 repositories, I am unable to provide extensive debugging support. Thank you for your understanding.

**Comment by RoskoMx** [comment]
Thank you very much for your answer. I follow many of your Youtube's content.
